#! /bin/bash

curl -O http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-repo-ubuntu1804_10.0.130-1_amd64.deb
sudo dpkg -i cuda-repo-ubuntu1804_10.0.130-1_amd64.deb
sudo apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
sudo apt-get update -y 
sudo apt-get install cuda -y 

sudo dpkg -i libcudnn7_7.6.5.32-1+cuda10.0_amd64.deb

sudo apt-get install python3-venv -y 
sudo apt install python3-pip -y 
sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3